name: Test_Every_Chapter

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  BUILD_TYPE: Release

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
        wget -q https://download.pytorch.org/libtorch/nightly/cpu/libtorch-shared-with-deps-latest.zip
        unzip -q libtorch-shared-with-deps-latest.zip
        sudo mv libtorch /
        export Torch_ROOT=/libtorch
        python3 -m pip -q install torch torchvision

  run_chap1:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - run: |
        cmake -B ./chap1/build -S ./chap1 -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DCMAKE_PREFIX_PATH=/libtorch
        cmake --build ./chap1/build --config ${{env.BUILD_TYPE}}
        python3 ./chap1/python/HelloWorld.py
        ./chap1/build/HelloWorld


  run_chap2:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - run: |
        cmake -B ./chap2/build -S ./chap2 -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DCMAKE_PREFIX_PATH=/libtorch
        cmake --build ./chap2/build --config ${{env.BUILD_TYPE}}
        python3 ./chap2/python/TensorBasics.py
        ./chap2/build/TensorBasics


  run_chap3:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - run: |
        cmake -B ./chap3/build -S ./chap3 -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DCMAKE_PREFIX_PATH=/libtorch
        cmake --build ./chap3/build --config ${{env.BUILD_TYPE}}
        python3 ./chap3/python/AutoGrad.py
        ./chap3/build/AutoGrad


  run_chap4:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - run: |
        cmake -B ./chap4/build -S ./chap4 -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DCMAKE_PREFIX_PATH=/libtorch
        cmake --build ./chap4/build --config ${{env.BUILD_TYPE}}
        python3 ./chap4/python/BasicModels.py
        ./chap4/build/BasicModels


  run_chap5:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - run: |
        cmake -B ./chap5/build -S ./chap5 -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DCMAKE_PREFIX_PATH=/libtorch
        cmake --build ./chap5/build --config ${{env.BUILD_TYPE}}
        python3 ./chap5/python/PracticeModels.py
        cd ./chap5/build
        ./PracticeModels
        cd ../../

